name: Prepare Arch Linux FakeFS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          # llvmとlldを復活！これで文句言わせへんぞ！
          brew install meson ninja wget llvm lld

      - name: Build fakefsify tool
        run: |
          meson setup build
          ninja -C build

      - name: Download Arch Linux ARM rootfs
        run: |
          wget http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz -O arch-rootfs.tar.gz

      - name: Run fakefsify
        run: |
          mkdir -p arch-fakefs
          
          FAKEFSIFY_CMD=$(find build -type f -name "fakefsify" | head -n 1)
          echo "Found fakefsify at: $FAKEFSIFY_CMD"
          
          $FAKEFSIFY_CMD arch-rootfs.tar.gz arch-fakefs/

      - name: Zip the FakeFS
        run: |
          cd arch-fakefs
          zip -r ../ArchLinux-FakeFS.zip .

      - name: Upload Arch FakeFS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ArchLinux-FakeFS
          path: ArchLinux-FakeFS.zip
