name: Prepare Arch Linux FakeFS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          brew install meson ninja wget llvm lld

      - name: Patch source code bug (fix nzcv error)
        run: |
          # 最新コミットのバグで struct cpu_state に nzcv がなくて落ちるので、
          # 該当行をコメントアウトするか、エラーが出ないように力技で書き換える！
          if [ -f "emu/cpu_backend.c" ]; then
            echo "Patching emu/cpu_backend.c..."
            sed -i.bak 's/cpu->nzcv/\/\* cpu->nzcv \*\//g' emu/cpu_backend.c
          fi

      - name: Build fakefsify tool
        run: |
          meson setup build
          ninja -C build

      - name: Download Arch Linux ARM rootfs
        run: |
          wget http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz -O arch-rootfs.tar.gz

      - name: Run fakefsify
        run: |
          mkdir -p arch-fakefs
          
          FAKEFSIFY_CMD=$(find build -type f -name "fakefsify" | head -n 1)
          echo "Found fakefsify at: $FAKEFSIFY_CMD"
          
          $FAKEFSIFY_CMD arch-rootfs.tar.gz arch-fakefs/

      - name: Zip the FakeFS
        run: |
          cd arch-fakefs
          zip -r ../ArchLinux-FakeFS.zip .

      - name: Upload Arch FakeFS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ArchLinux-FakeFS
          path: ArchLinux-FakeFS.zip
