name: Upload Build (Custom IPA)

on:
  workflow_dispatch:

jobs:
  upload-build:
    runs-on: macos-15
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install deps
        run: |
          brew install ninja lld llvm meson

      - name: Grant execution rights
        run: |
          chmod +x tools/package_arm64_trollstore_ipa.sh

      - name: Build TIPA with script
        run: |
          ./tools/package_arm64_trollstore_ipa.sh

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iSH-ARM64-TrollStore
          path: build/iSH-ARM64-JIT-TrollStore.tipa
